package config
import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"github.com/amiridev-org/irangate-ov/pkg/database"
	"github.com/amiridev-org/irangate-ov/pkg/utils"
)
const (
	OpenVPNConfigPath = "/etc/openvpn/server/server.conf"
)
type Manager struct {
	db *database.DB
}
func New(db *database.DB) *Manager {
	return &Manager{db: db}
}
func (m *Manager) GetConfig() (*database.Settings, error) {
	return m.db.GetSettings()
}
func (m *Manager) UpdateConfig(settings database.Settings) error {
	logger := utils.GetLogger()
	logger.Info("Updating server configuration...")
	if err := m.validateSettings(settings); err != nil {
		return fmt.Errorf("invalid settings: %v", err)
	}
	if err := m.db.UpdateSettings(settings); err != nil {
		return fmt.Errorf("failed to update settings: %v", err)
	}
	if err := m.regenerateServerConfig(settings); err != nil {
		return fmt.Errorf("failed to regenerate server config: %v", err)
	}
	logger.Info("Server configuration updated successfully")
	return nil
}
func (m *Manager) SetValue(key string, value interface{}) error {
	settings, err := m.db.GetSettings()
	if err != nil {
		return fmt.Errorf("failed to get settings: %v", err)
	}
	settingsValue := reflect.ValueOf(settings).Elem()
	field := settingsValue.FieldByNameFunc(func(n string) bool {
		return strings.EqualFold(n, key)
	})
	if !field.IsValid() {
		return fmt.Errorf("invalid setting key: %s", key)
	}
	convertedValue := reflect.ValueOf(value)
	if field.Type() != convertedValue.Type() {
		return fmt.Errorf("invalid value type for %s: expected %v, got %v",
			key, field.Type(), convertedValue.Type())
	}
	field.Set(convertedValue)
	return m.UpdateConfig(*settings)
}
func (m *Manager) BackupConfig() (string, error) {
	logger := utils.GetLogger()
	logger.Info("Creating configuration backup...")
	settings, err := m.db.GetSettings()
	if err != nil {
		return "", fmt.Errorf("failed to get settings: %v", err)
	}
	backupDir := settings.BackupPath
	if backupDir == "" {
		backupDir = filepath.Join(m.db.GetPath(), "backups")
	}
	if err := os.MkdirAll(backupDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create backup directory: %v", err)
	}
	backupFile := filepath.Join(backupDir, "config_backup.json")
	data, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return "", fmt.Errorf("failed to marshal settings: %v", err)
	}
	if err := os.WriteFile(backupFile, data, 0600); err != nil {
		return "", fmt.Errorf("failed to write backup file: %v", err)
	}
	logger.Infof("Configuration backed up to: %s", backupFile)
	return backupFile, nil
}
func (m *Manager) RestoreConfig(backupFile string) error {
	logger := utils.GetLogger()
	logger.Infof("Restoring configuration from: %s", backupFile)
	data, err := os.ReadFile(backupFile)
	if err != nil {
		return fmt.Errorf("failed to read backup file: %v", err)
	}
	var settings database.Settings
	if err := json.Unmarshal(data, &settings); err != nil {
		return fmt.Errorf("failed to unmarshal settings: %v", err)
	}
	return m.UpdateConfig(settings)
}
func (m *Manager) ValidateConfig() error {
	settings, err := m.db.GetSettings()
	if err != nil {
		return fmt.Errorf("failed to get settings: %v", err)
	}
	return m.validateSettings(*settings)
}
func (m *Manager) validateSettings(settings database.Settings) error {
	if settings.ServerPort < 1 || settings.ServerPort > 65535 {
		return fmt.Errorf("invalid port number: %d", settings.ServerPort)
	}
	if settings.Protocol != "udp" && settings.Protocol != "tcp" {
		return fmt.Errorf("invalid protocol: %s", settings.Protocol)
	}
	validCiphers := []string{
		"AES-256-GCM",
		"AES-128-GCM",
		"AES-256-CBC",
		"AES-128-CBC",
	}
	validCipher := false
	for _, c := range validCiphers {
		if settings.Cipher == c {
			validCipher = true
			break
		}
	}
	if !validCipher {
		return fmt.Errorf("invalid cipher: %s", settings.Cipher)
	}
	if settings.MTU < 576 || settings.MTU > 1500 {
		return fmt.Errorf("invalid MTU value: %d", settings.MTU)
	}
	for _, dns := range settings.DNS {
		if !utils.IsValidIP(dns) {
			return fmt.Errorf("invalid DNS server address: %s", dns)
		}
	}
	return nil
}
func (m *Manager) regenerateServerConfig(settings database.Settings) error {
	config := fmt.Sprintf(`# OpenVPN Server Configuration
# Generated by IranGate CLI
port %d
proto %s
dev tun
# Certificates
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server.crt
key /etc/openvpn/easy-rsa/pki/private/server.key
dh /etc/openvpn/easy-rsa/pki/dh.pem
tls-crypt /etc/openvpn/easy-rsa/tc.key
crl-verify /etc/openvpn/easy-rsa/pki/crl.pem
# Network Configuration
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist /var/log/openvpn/ipp.txt
# Push routes to client
push "redirect-gateway def1 bypass-dhcp"
%s
# Performance
keepalive 10 120
cipher %s
auth SHA256
user nobody
group nogroup
persist-key
persist-tun
# Logging
status /var/log/openvpn/openvpn-status.log
log-append /var/log/openvpn/openvpn.log
verb 3
# Additional Settings
%s
max-clients 100
`,
		settings.ServerPort,
		settings.Protocol,
		m.getDNSPushConfig(settings.DNS),
		settings.Cipher,
		m.getAdditionalConfig(settings),
	)
	if err := os.WriteFile(OpenVPNConfigPath, []byte(config), 0644); err != nil {
		return fmt.Errorf("failed to write server config: %v", err)
	}
	return nil
}
func (m *Manager) getDNSPushConfig(dns []string) string {
	var config strings.Builder
	if len(dns) > 0 {
		for _, server := range dns {
			if server != "" {
				config.WriteString(fmt.Sprintf("push \"dhcp-option DNS %s\"\n", server))
			}
		}
	}
	return config.String()
}
func (m *Manager) getAdditionalConfig(settings database.Settings) string {
	var config strings.Builder
	if settings.MTU > 0 {
		config.WriteString(fmt.Sprintf("tun-mtu %d\n", settings.MTU))
	}
	if settings.IPv6Enabled {
		config.WriteString("proto-force " + settings.Protocol + "6\n")
		config.WriteString("server-ipv6 2001:db8:0:123::/64\n")
	}
	return config.String()
}